defmodule Advent.Year2024.Day6Test do
  @input "....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
"
  use DayTemplate, day: 6, input: @input, part_a: 41, part_b: 6

  test "loop is recognised successfully" do
    alias Advent.Year2024.Day6

    input = "....#.....
.........#
..........
..#.......
.......#..
..........
.#.#^.....
........#.
#.........
......#...
"

    parsed = Day6.parse(input)
    assert :looped = Day6.process(parsed)
  end
end
