defmodule Advent.Year2024.Day6Test do
  @input "....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
"
  use DayTemplate, day: 6, input: @input, part_a: 41
end
