defmodule Advent.Year2024.Day8Test do
  @input "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"

  use DayTemplate, day: 8, input: @input, part_a: 14, part_b: 34

  # Consider testing antinode position calc
end
